import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen mx-auto max-w-[1920px] my-2">
      <div className=" bg-base-200 rounded-box ml-2">{children}</div>
    </div>
  );
}
